/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentUI;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import ui.MainJFrame;

/**
 *
 * @author asus
 */
public class StudentDashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form stdPageJPanel
     */
    JPanel userProcessContainer;
    MainJFrame mainFrame;
    public StudentDashboardPanel(MainJFrame mainFrame,JPanel userProcessContainer) {
        initComponents();
        this.mainFrame=mainFrame;
        this.userProcessContainer = userProcessContainer;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registrationbtn = new javax.swing.JButton();
        Coursesbtn = new javax.swing.JButton();
        Profilebtn = new javax.swing.JButton();
        Graduationbtn = new javax.swing.JButton();

        Registrationbtn.setText("Registration");
        Registrationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationbtnActionPerformed(evt);
            }
        });

        Coursesbtn.setText("Courses");
        Coursesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesbtnActionPerformed(evt);
            }
        });

        Profilebtn.setText("Profile");
        Profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilebtnActionPerformed(evt);
            }
        });

        Graduationbtn.setText("Graduation");
        Graduationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraduationbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(Coursesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Registrationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Profilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Graduationbtn)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Coursesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registrationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Graduationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(305, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CoursesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesbtnActionPerformed
        // TODO add your handling code here:
        StudentCoursesPanel studentCourses = new StudentCoursesPanel(this.mainFrame,this.userProcessContainer);
        userProcessContainer.add("student course",studentCourses);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_CoursesbtnActionPerformed

    private void ProfilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilebtnActionPerformed
        // TODO add your handling code here:
        stdProfileJPanel studentProfile = new stdProfileJPanel(this.mainFrame,this.userProcessContainer);
        userProcessContainer.add("student profile",studentProfile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ProfilebtnActionPerformed

    private void GraduationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraduationbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraduationbtnActionPerformed

    private void RegistrationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationbtnActionPerformed
        // TODO add your handling code here:
        stdRegistrationJPanel studentRegistration = new stdRegistrationJPanel(this.mainFrame,this.userProcessContainer);
        userProcessContainer.add("student course",studentRegistration);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_RegistrationbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Coursesbtn;
    private javax.swing.JButton Graduationbtn;
    private javax.swing.JButton Profilebtn;
    private javax.swing.JButton Registrationbtn;
    // End of variables declaration//GEN-END:variables
}
