/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package professorUI;

import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.MainJFrame;

/**
 *
 * @author User
 */
public class professorDashBoard extends javax.swing.JPanel {

    /**
     * Creates new form professorDashBoard
     */
    JPanel userProcessContainer;
    MainJFrame mainFrame;

    professorDashBoard(MainJFrame mainFrame, JPanel userProcessContainer) {
        initComponents();
        this.mainFrame=mainFrame;
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProfile = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnStudents = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        btnCurrentClasses = new javax.swing.JButton();

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnHistory.setText("Teaching History");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        btnStudents.setText("Students");
        btnStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsActionPerformed(evt);
            }
        });

        btnRanking.setText("Ranking");
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });

        btnCurrentClasses.setText("Current Classes");
        btnCurrentClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentClassesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProfile)
                    .addComponent(btnRanking))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHistory)
                        .addGap(55, 55, 55)
                        .addComponent(btnStudents))
                    .addComponent(btnCurrentClasses))
                .addContainerGap(588, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfile)
                    .addComponent(btnHistory)
                    .addComponent(btnStudents))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRanking)
                    .addComponent(btnCurrentClasses))
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        proProfileJPanel proProfile= new proProfileJPanel(this.mainFrame,this.userProcessContainer);
        userProcessContainer.add("proProfileJPanel",proProfile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        proTeachingHistoryJPanel proHistory= new proTeachingHistoryJPanel(this.mainFrame,this.userProcessContainer);
        userProcessContainer.add("proTeachingHistory",proHistory);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
        // TODO add your handling code here:
        proStudentsJPanel proStudent= new proStudentsJPanel(this.mainFrame,this.userProcessContainer);
        userProcessContainer.add("proStudentsJPanel",proStudent);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // TODO add your handling code here:
        proRankingJPanel proRank= new proRankingJPanel(this.mainFrame,this.userProcessContainer);
        userProcessContainer.add("proRankingJPanel",proRank);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnCurrentClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentClassesActionPerformed
        // TODO add your handling code here:
        proCurrentClassesJPanel proCurrent= new proCurrentClassesJPanel(this.mainFrame,this.userProcessContainer);
        userProcessContainer.add("proCurrentClassesJPanel",proCurrent);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCurrentClassesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCurrentClasses;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnStudents;
    // End of variables declaration//GEN-END:variables
}
