/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import UserInterface.WorkAreas.MainAppFrame;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author smatcha
 */
public class FacultyDashboard extends javax.swing.JPanel {

    /**
     * Creates new form FacultyDashboard
     */
    MainAppFrame mainFrame;
    JPanel userProcessContainer;

    public FacultyDashboard(MainAppFrame mainFrame, JPanel userProcessContainer) {
        initComponents();
        this.mainFrame = mainFrame;
        this.userProcessContainer = userProcessContainer;
        
        this.mainFrame.getBtnProfile().setVisible(true);
        this.mainFrame.getBtnSignOut().setVisible(true);
        
        this.mainFrame.getLoginBtn().setVisible(false);
        this.mainFrame.getSignUpBtn().setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCurrentClasses = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnCurrentClasses1 = new javax.swing.JButton();
        btnCurrentClasses2 = new javax.swing.JButton();
        btnCurrentClasses3 = new javax.swing.JButton();

        btnCurrentClasses.setText("Current Claseses");
        btnCurrentClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentClassesActionPerformed(evt);
            }
        });

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnCurrentClasses1.setText("Teaching History");
        btnCurrentClasses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentClasses1ActionPerformed(evt);
            }
        });

        btnCurrentClasses2.setText("Student Ranking");
        btnCurrentClasses2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentClasses2ActionPerformed(evt);
            }
        });

        btnCurrentClasses3.setText("Students");
        btnCurrentClasses3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentClasses3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCurrentClasses2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCurrentClasses3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCurrentClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCurrentClasses1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(343, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnProfile)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCurrentClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCurrentClasses1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCurrentClasses2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCurrentClasses3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCurrentClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentClassesActionPerformed
        // TODO add your handling code here:
        CurrentClassesPanel currentclassespanel= new CurrentClassesPanel(this.mainFrame,this.userProcessContainer);
        userProcessContainer.add("CurrentClassesPanel",currentclassespanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnCurrentClassesActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnCurrentClasses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentClasses1ActionPerformed
        // TODO add your handling code here:
        TeachingHistoryPanel panel= new TeachingHistoryPanel(this.mainFrame,this.userProcessContainer);
        userProcessContainer.add("TeachingHistoryPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCurrentClasses1ActionPerformed

    private void btnCurrentClasses2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentClasses2ActionPerformed
        // TODO add your handling code here:
        RankingPanel rankpanel= new RankingPanel(this.mainFrame,this.userProcessContainer);
        userProcessContainer.add("RankingPanel",rankpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCurrentClasses2ActionPerformed

    private void btnCurrentClasses3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentClasses3ActionPerformed
        // TODO add your handling code here:
        StudentsDataPanel stdsignupPanel = new StudentsDataPanel(this.mainFrame, this.userProcessContainer);
userProcessContainer.add("Student Signup Panel", stdsignupPanel);
CardLayout layout = (CardLayout) userProcessContainer.getLayout();
layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCurrentClasses3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCurrentClasses;
    private javax.swing.JButton btnCurrentClasses1;
    private javax.swing.JButton btnCurrentClasses2;
    private javax.swing.JButton btnCurrentClasses3;
    private javax.swing.JButton btnProfile;
    // End of variables declaration//GEN-END:variables
}
